#ifndef __LIBC_ERRNO_H
#define __LIBC_ERRNO_H

enum {
	ERANGE,
	EDOM,
	EILSEQ,
	E2BIG,
	EACCES,
	EADDRINUSE,
	EADDRNOTAVAIL,
	EAFNOSUPPORT,
	EAGAIN,
	EALREADY,
	EBADF,
	EBADMSG,
	EBUSY,
	ECANCELED,
	ECHILD,
	ECONNABORTED,
	ECONNREFUSED,
	ECONNRESET,
	EDEADLK,
	EDESTADDRREQ,
	EEXIST,
	EFAULT,
	EFBIG,
	EHOSTUNREACH,
	EIDRM,
	EINPROGRESS,
	EINTR,
	EINVAL,
	EIO,
	EISCONN,
	EISDIR,
	ELOOP,
	EMFILE,
	EMLINK,
	EMSGSIZE,
	ENAMETOOLONG,
	ENETDOWN,
	ENETRESET,
	ENETUNREACH,
	ENFILE,
	ENOBUFS,
	ENODATA,
	ENODEV,
	ENOENT,
	ENOEXEC,
	ENOLCK,
	ENOLINK,
	ENOMEM,
	ENOMSG,
	ENOPROTOOPT,
	ENOSPC,
	ENOSR,
	ENOSTR,
	ENOSYS,
	ENOTCONN,
	ENOTDIR,
	ENOTEMPTY,
	ENOTRECOVERABLE,
	ENOTSOCK,
	ENOTSUP,
	ENOTTY,
	ENXIO,
	EOPNOTSUPP,
	EOVERFLOW,
	EOWNERDEAD,
	EPERM,
	EPIPE,
	EPROTO,
	EPROTONOSUPPORT,
	EPROTOTYPE,
	EROFS,
	ESPIPE,
	ESRCH,
	ETIME,
	ETIMEDOUT,
	ETXTBSY,
	EWOULDBLOCK,
	EXDEV,
};

#define ERANGE (ERANGE)
#define EDOM (EDOM)
#define EILSEQ (EILSEQ)
#define E2BIG (E2BIG)
#define EACCES (EACCES)
#define EADDRINUSE (EADDRINUSE)
#define EADDRNOTAVAIL (EADDRNOTAVAIL)
#define EAFNOSUPPORT (EAFNOSUPPORT)
#define EAGAIN (EAGAIN)
#define EALREADY (EALREADY)
#define EBADF (EBADF)
#define EBADMSG (EBADMSG)
#define EBUSY (EBUSY)
#define ECANCELED (ECANCELED)
#define ECHILD (ECHILD)
#define ECONNABORTED (ECONNABORTED)
#define ECONNREFUSED (ECONNREFUSED)
#define ECONNRESET (ECONNRESET)
#define EDEADLK (EDEADLK)
#define EDESTADDRREQ (EDESTADDRREQ)
#define EEXIST (EEXIST)
#define EFAULT (EFAULT)
#define EFBIG (EFBIG)
#define EHOSTUNREACH (EHOSTUNREACH)
#define EIDRM (EIDRM)
#define EINPROGRESS (EINPROGRESS)
#define EINTR (EINTR)
#define EINVAL (EINVAL)
#define EIO (EIO)
#define EISCONN (EISCONN)
#define EISDIR (EISDIR)
#define ELOOP (ELOOP)
#define EMFILE (EMFILE)
#define EMLINK (EMLINK)
#define EMSGSIZE (EMSGSIZE)
#define ENAMETOOLONG (ENAMETOOLONG)
#define ENETDOWN (ENETDOWN)
#define ENETRESET (ENETRESET)
#define ENETUNREACH (ENETUNREACH)
#define ENFILE (ENFILE)
#define ENOBUFS (ENOBUFS)
#define ENODATA (ENODATA)
#define ENODEV (ENODEV)
#define ENOENT (ENOENT)
#define ENOEXEC (ENOEXEC)
#define ENOLCK (ENOLCK)
#define ENOLINK (ENOLINK)
#define ENOMEM (ENOMEM)
#define ENOMSG (ENOMSG)
#define ENOPROTOOPT (ENOPROTOOPT)
#define ENOSPC (ENOSPC)
#define ENOSR (ENOSR)
#define ENOSTR (ENOSTR)
#define ENOSYS (ENOSYS)
#define ENOTCONN (ENOTCONN)
#define ENOTDIR (ENOTDIR)
#define ENOTEMPTY (ENOTEMPTY)
#define ENOTRECOVERABLE (ENOTRECOVERABLE)
#define ENOTSOCK (ENOTSOCK)
#define ENOTSUP (ENOTSUP)
#define ENOTTY (ENOTTY)
#define ENXIO (ENXIO)
#define EOPNOTSUPP (EOPNOTSUPP)
#define EOVERFLOW (EOVERFLOW)
#define EOWNERDEAD (EOWNERDEAD)
#define EPERM (EPERM)
#define EPIPE (EPIPE)
#define EPROTO (EPROTO)
#define EPROTONOSUPPORT (EPROTONOSUPPORT)
#define EPROTOTYPE (EPROTOTYPE)
#define EROFS (EROFS)
#define ESPIPE (ESPIPE)
#define ESRCH (ESRCH)
#define ETIME (ETIME)
#define ETIMEDOUT (ETIMEDOUT)
#define ETXTBSY (ETXTBSY)
#define EWOULDBLOCK (EWOULDBLOCK)
#define EXDEV (EXDEV)

extern int errno;

#endif
